// <auto-generated />
using System;
using CityApp.Shared.Entities.BDSqlServerCityApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityApp.Shared.Migrations
{
    [DbContext(typeof(CityAppContext))]
    [Migration("20220725054849_Tablas_base")]
    partial class Tablas_base
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContacto"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoOpcion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoOpcion2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", b =>
                {
                    b.Property<int>("IdContadorAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContadorAcceso"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("Intento")
                        .HasColumnType("int");

                    b.HasKey("IdContadorAcceso");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("ContadoresAccesos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"), 1L, 1);

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdRol");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", b =>
                {
                    b.Property<int>("IdEstatusCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusCuenta"), 1L, 1);

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<bool>("PerfilCompleto")
                        .HasColumnType("bit");

                    b.HasKey("IdEstatusCuenta");

                    b.HasIndex("IdCuenta")
                        .IsUnique()
                        .HasFilter("[IdCuenta] IS NOT NULL");

                    b.ToTable("EstatusCuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", b =>
                {
                    b.Property<int>("IdTokenActualizarPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenActualizarPassword"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenActualizarPassword");

                    b.ToTable("TokensActualizarPassword");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", b =>
                {
                    b.Property<int>("IdTokenContadorAccesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenContadorAccesos"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenContadorAccesos");

                    b.ToTable("TokensContadorAcceso");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", b =>
                {
                    b.Property<int>("IdTokenVerificacionCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenVerificacionCorreo"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenVerificacionCorreo");

                    b.ToTable("TokensVerificacionCorreo");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("Contacto")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("ContadorAcceso")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", "Rol")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("EstatusCuenta")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", "IdCuenta");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("Usuario")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.Navigation("Contacto");

                    b.Navigation("ContadorAcceso");

                    b.Navigation("EstatusCuenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", b =>
                {
                    b.Navigation("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
