// <auto-generated />
using System;
using CityApp.Shared.Entities.BDSqlServerCityApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityApp.Shared.Migrations
{
    [DbContext(typeof(CityAppContext))]
    [Migration("20220808071205_reportesCiudadanoRestrucV2")]
    partial class reportesCiudadanoRestrucV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoNoticia", b =>
                {
                    b.Property<int>("IdArchivoNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivoNoticia"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNoticia")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArchivoNoticia");

                    b.HasIndex("IdNoticia");

                    b.ToTable("ArchivosNoticia");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContacto"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoOpcion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoOpcion2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", b =>
                {
                    b.Property<int>("IdContadorAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContadorAcceso"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("Intento")
                        .HasColumnType("int");

                    b.HasKey("IdContadorAcceso");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("ContadoresAccesos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"), 1L, 1);

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdRol");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionReporteCiudadano", b =>
                {
                    b.Property<int>("IdDireccionReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionReporteCiudadano"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVercionReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionReporteCiudadano");

                    b.HasIndex("IdVercionReporteCiudadano")
                        .IsUnique();

                    b.ToTable("DireccionesReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionUsuario", b =>
                {
                    b.Property<int>("IdDireccionUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionUsuario"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionUsuario");

                    b.HasIndex("IdCuenta");

                    b.ToTable("DireccionesUsuario");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", b =>
                {
                    b.Property<int>("IdEstatusCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusCuenta"), 1L, 1);

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("bit");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<bool>("PerfilCompleto")
                        .HasColumnType("bit");

                    b.HasKey("IdEstatusCuenta");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("EstatusCuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusReporteCiudadano", b =>
                {
                    b.Property<int>("IdEstatusReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusReporteCiudadano"), 1L, 1);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatusReporteCiudadano");

                    b.ToTable("EstatusReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaReporteCiudadano", b =>
                {
                    b.Property<int>("IdEnvidenciaReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvidenciaReporteCiudadano"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVercionReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnvidenciaReporteCiudadano");

                    b.HasIndex("IdVercionReporteCiudadano");

                    b.ToTable("EvidenciasReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaSolucionReporteCiudadano", b =>
                {
                    b.Property<int>("IdEnvidenciaSolucionReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvidenciaSolucionReporteCiudadano"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnvidenciaSolucionReporteCiudadano");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdReporteCiudadano");

                    b.ToTable("EvidenciasSolucionReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Noticia", b =>
                {
                    b.Property<int>("IdNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNoticia"), 1L, 1);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncaleWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnlaceFacebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNoticia");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", b =>
                {
                    b.Property<int>("IdReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporteCiudadano"), 1L, 1);

                    b.Property<int?>("CuentaIdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoReporteCiudadano")
                        .HasColumnType("int");

                    b.HasKey("IdReporteCiudadano");

                    b.HasIndex("CuentaIdCuenta");

                    b.HasIndex("IdEstatusReporteCiudadano");

                    b.HasIndex("IdTipoReporteCiudadano");

                    b.ToTable("ReportesCiudadanos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoReporteCiudadano", b =>
                {
                    b.Property<int>("IdTipoReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoReporteCiudadano"), 1L, 1);

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoReporteCiudadano");

                    b.ToTable("TiposReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoTokenLogin", b =>
                {
                    b.Property<int>("IdTipoTokenLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTokenLogin"), 1L, 1);

                    b.Property<string>("TipoToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoTokenLogin");

                    b.ToTable("TiposTokenLogin");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", b =>
                {
                    b.Property<int>("IdTokenActualizarPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenActualizarPassword"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenActualizarPassword");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("TokensActualizarPassword");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", b =>
                {
                    b.Property<int>("IdTokenContadorAccesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenContadorAccesos"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenContadorAccesos");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("TokensContadorAcceso");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenLogin", b =>
                {
                    b.Property<int>("IdTokenLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenLogin"), 1L, 1);

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTokenLogin")
                        .HasColumnType("int");

                    b.Property<bool>("MantenerSesion")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenLogin");

                    b.HasIndex("IdTipoTokenLogin");

                    b.ToTable("TokensLogin");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", b =>
                {
                    b.Property<int>("IdTokenVerificacionCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenVerificacionCorreo"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenVerificacionCorreo");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("TokensVerificacionCorreo");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", b =>
                {
                    b.Property<int>("IdVercionReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVercionReporteCiudadano"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdReporteCiudadano")
                        .HasColumnType("int");

                    b.HasKey("IdVercionReporteCiudadano");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdReporteCiudadano");

                    b.ToTable("VercionesReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoNoticia", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Noticia", "Noticia")
                        .WithMany("ArchivosNoticia")
                        .HasForeignKey("IdNoticia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("Contacto")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("ContadorAcceso")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", "Rol")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", "VercionReporteCiudadano")
                        .WithOne("DireccionReporteCiudadano")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionReporteCiudadano", "IdVercionReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VercionReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionUsuario", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany("DireccionesUsuario")
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("EstatusCuenta")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", "VercionReporteCiudadano")
                        .WithMany("EvidenciasReporteCiudadano")
                        .HasForeignKey("IdVercionReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VercionReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaSolucionReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", "ReporteCiudadano")
                        .WithMany("EvidenciasSolucionReporteCiudadano")
                        .HasForeignKey("IdReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("ReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", null)
                        .WithMany("ReportesCiudadanos")
                        .HasForeignKey("CuentaIdCuenta");

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusReporteCiudadano", "EstatusReporteCiudadano")
                        .WithMany("ReportesCiudadanos")
                        .HasForeignKey("IdEstatusReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoReporteCiudadano", "TipoReporteCiudadano")
                        .WithMany("ReportesCiudadanos")
                        .HasForeignKey("IdTipoReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstatusReporteCiudadano");

                    b.Navigation("TipoReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("TokenActualizarPassword")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("TokenContadorAccesos")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenLogin", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoTokenLogin", "TipoTokenLogin")
                        .WithMany()
                        .HasForeignKey("IdTipoTokenLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTokenLogin");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("TokenVerificacionCorreo")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("Usuario")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", "ReporteCiudadano")
                        .WithMany("VercionesReporteCiudadano")
                        .HasForeignKey("IdReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("ReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.Navigation("Contacto");

                    b.Navigation("ContadorAcceso");

                    b.Navigation("DireccionesUsuario");

                    b.Navigation("EstatusCuenta");

                    b.Navigation("ReportesCiudadanos");

                    b.Navigation("TokenActualizarPassword");

                    b.Navigation("TokenContadorAccesos");

                    b.Navigation("TokenVerificacionCorreo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusReporteCiudadano", b =>
                {
                    b.Navigation("ReportesCiudadanos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Noticia", b =>
                {
                    b.Navigation("ArchivosNoticia");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", b =>
                {
                    b.Navigation("EvidenciasSolucionReporteCiudadano");

                    b.Navigation("VercionesReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoReporteCiudadano", b =>
                {
                    b.Navigation("ReportesCiudadanos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", b =>
                {
                    b.Navigation("DireccionReporteCiudadano");

                    b.Navigation("EvidenciasReporteCiudadano");
                });
#pragma warning restore 612, 618
        }
    }
}
