// <auto-generated />
using System;
using CityApp.Shared.Entities.BDSqlServerCityApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityApp.Shared.Migrations
{
    [DbContext(typeof(CityAppContext))]
    [Migration("20221101213520_TipoAtencion")]
    partial class TipoAtencion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Agenda", b =>
                {
                    b.Property<int>("IdAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgenda"), 1L, 1);

                    b.Property<string>("EnlaceWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAgenda");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"), 1L, 1);

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusAlerta")
                        .HasColumnType("int");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdEstatusAlerta");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoAgenda", b =>
                {
                    b.Property<int>("IdArchivoAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivoAgenda"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAgenda")
                        .HasColumnType("int");

                    b.Property<int?>("IdNoticia")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArchivoAgenda");

                    b.HasIndex("IdNoticia");

                    b.ToTable("ArchivosAgenda");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoLugarTuristico", b =>
                {
                    b.Property<int>("IdArchivoLugarTuristico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivoLugarTuristico"), 1L, 1);

                    b.Property<DateTime>("FechaArchivo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLugarTuristico")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArchivoLugarTuristico");

                    b.HasIndex("IdLugarTuristico");

                    b.ToTable("ArchivosLugaresTuristicos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoNoticia", b =>
                {
                    b.Property<int>("IdArchivoNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArchivoNoticia"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNoticia")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArchivoNoticia");

                    b.HasIndex("IdNoticia");

                    b.ToTable("ArchivosNoticia");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.CaracteristicaLugarTuristico", b =>
                {
                    b.Property<int>("IdCaracteristicaLugarTuristico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaracteristicaLugarTuristico"), 1L, 1);

                    b.Property<string>("Caracteristica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLugarTuristico")
                        .HasColumnType("int");

                    b.Property<string>("NombreCaracteristica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCaracteristicaLugarTuristico");

                    b.HasIndex("IdLugarTuristico");

                    b.ToTable("CaracteristicasLugaresTuristicos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContacto"), 1L, 1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoOpcion1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoOpcion2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContactoMunicipio", b =>
                {
                    b.Property<int>("IdContactoMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactoMunicipio"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContactoMunicipio");

                    b.ToTable("ContactosMunicipio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContactoSeguridadPublica", b =>
                {
                    b.Property<int>("IdContactoSeguridadPublica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactoSeguridadPublica"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTipoAtencionContacto")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContactoSeguridadPublica");

                    b.HasIndex("IdTipoAtencionContacto");

                    b.ToTable("ContactosSeguridadPublica");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", b =>
                {
                    b.Property<int>("IdContadorAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContadorAcceso"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("Intento")
                        .HasColumnType("int");

                    b.HasKey("IdContadorAcceso");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("ContadoresAccesos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"), 1L, 1);

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdRol");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionAlerta", b =>
                {
                    b.Property<int>("IdDireccionAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionAlerta"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAlerta")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionAlerta");

                    b.HasIndex("IdAlerta")
                        .IsUnique();

                    b.ToTable("DireccionesAlertas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionLugarTuristico", b =>
                {
                    b.Property<int>("IdDireccionLugarTuristico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionLugarTuristico"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLugarTuristico")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionLugarTuristico");

                    b.HasIndex("IdLugarTuristico")
                        .IsUnique();

                    b.ToTable("DireccionesLugaresTuristicos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionPropietarioPredio", b =>
                {
                    b.Property<int>("IdDireccionPropietarioPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionPropietarioPredio"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPropietarioPredio")
                        .HasColumnType("int");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Poblacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionPropietarioPredio");

                    b.HasIndex("IdPropietarioPredio")
                        .IsUnique();

                    b.ToTable("DireccionesPropietarioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionReporteCiudadano", b =>
                {
                    b.Property<int>("IdDireccionReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionReporteCiudadano"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVercionReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionReporteCiudadano");

                    b.HasIndex("IdVercionReporteCiudadano")
                        .IsUnique();

                    b.ToTable("DireccionesReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionUsuario", b =>
                {
                    b.Property<int>("IdDireccionUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionUsuario"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDireccionUsuario");

                    b.HasIndex("IdCuenta");

                    b.ToTable("DireccionesUsuario");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DomicilioPredio", b =>
                {
                    b.Property<int>("IdDomicilioPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDomicilioPredio"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPredio")
                        .HasColumnType("int");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Poblacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDomicilioPredio");

                    b.HasIndex("IdPredio")
                        .IsUnique();

                    b.ToTable("DomiciliosPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusAlerta", b =>
                {
                    b.Property<int>("IdEstatusAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusAlerta"), 1L, 1);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatusAlerta");

                    b.ToTable("EstatusAlertas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", b =>
                {
                    b.Property<int>("IdEstatusCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusCuenta"), 1L, 1);

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("bit");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<bool>("PerfilCompleto")
                        .HasColumnType("bit");

                    b.HasKey("IdEstatusCuenta");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("EstatusCuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusPago", b =>
                {
                    b.Property<int>("IdEstatusPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusPago"), 1L, 1);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatusPago");

                    b.ToTable("EstatusPago");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusReporteCiudadano", b =>
                {
                    b.Property<int>("IdEstatusReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusReporteCiudadano"), 1L, 1);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatusReporteCiudadano");

                    b.ToTable("EstatusReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaReporteCiudadano", b =>
                {
                    b.Property<int>("IdEnvidenciaReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvidenciaReporteCiudadano"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdVercionReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnvidenciaReporteCiudadano");

                    b.HasIndex("IdVercionReporteCiudadano");

                    b.ToTable("EvidenciasReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaSolucionReporteCiudadano", b =>
                {
                    b.Property<int>("IdEnvidenciaSolucionReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvidenciaSolucionReporteCiudadano"), 1L, 1);

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnvidenciaSolucionReporteCiudadano");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdReporteCiudadano");

                    b.ToTable("EvidenciasSolucionReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.InformacionDomicilioPredio", b =>
                {
                    b.Property<int>("IdInformacionDomicilioPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInformacionDomicilioPredio"), 1L, 1);

                    b.Property<string>("CalidadConstruccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriaConstruccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDomicilioPredio")
                        .HasColumnType("int");

                    b.Property<double>("MtsArea")
                        .HasColumnType("float");

                    b.Property<double>("MtsConstruccion")
                        .HasColumnType("float");

                    b.Property<double>("MtsFondo")
                        .HasColumnType("float");

                    b.Property<double>("MtsFrente")
                        .HasColumnType("float");

                    b.Property<string>("TipoConstruccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsoConstruccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorComercial")
                        .HasColumnType("float");

                    b.Property<string>("ZonaEconomica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInformacionDomicilioPredio");

                    b.HasIndex("IdDomicilioPredio")
                        .IsUnique();

                    b.ToTable("InformacionDomicilioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.LugarTuristico", b =>
                {
                    b.Property<int>("IdLugarTuristico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLugarTuristico"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFundacionConstruccionApertura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoLugarTuristico")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLugarTuristico");

                    b.HasIndex("IdTipoLugarTuristico");

                    b.ToTable("LugaresTuristicos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Normatividad", b =>
                {
                    b.Property<int>("IdNormatividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNormatividad"), 1L, 1);

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNormatividad");

                    b.ToTable("Normatividades");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Noticia", b =>
                {
                    b.Property<int>("IdNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNoticia"), 1L, 1);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncaleWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnlaceFacebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNoticia");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"), 1L, 1);

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusPago")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdEstatusPago");

                    b.HasIndex("IdTipoPago");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.PagoPredio", b =>
                {
                    b.Property<int>("IdPagoPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagoPredio"), 1L, 1);

                    b.Property<string>("Anotaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FehcaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPredio")
                        .HasColumnType("int");

                    b.Property<double>("Normal")
                        .HasColumnType("float");

                    b.Property<int>("PredioId")
                        .HasColumnType("int");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Recargo")
                        .HasColumnType("float");

                    b.Property<double>("Rezago")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<double>("Valuado")
                        .HasColumnType("float");

                    b.HasKey("IdPagoPredio");

                    b.HasIndex("IdPredio");

                    b.ToTable("PagosPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Patrulla", b =>
                {
                    b.Property<int>("IdPatrulla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatrulla"), 1L, 1);

                    b.Property<string>("NumeroEconomico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPatrulla");

                    b.ToTable("Patrullas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Predio", b =>
                {
                    b.Property<int>("IdPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPredio"), 1L, 1);

                    b.Property<bool>("Atrasado")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaveCatastral")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPredio");

                    b.ToTable("Predios");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.PropietarioPredio", b =>
                {
                    b.Property<int>("IdPropietarioPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropietarioPredio"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdPredio")
                        .HasColumnType("int");

                    b.Property<string>("Propietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropietarioPredio");

                    b.HasIndex("IdPredio")
                        .IsUnique();

                    b.ToTable("PropietariosPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.RedSocialMunicipio", b =>
                {
                    b.Property<int>("IdRedSocialMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRedSocialMunicipio"), 1L, 1);

                    b.Property<int>("IdContactoMunicipio")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoRedSocial")
                        .HasColumnType("int");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRedSocialMunicipio");

                    b.HasIndex("IdContactoMunicipio");

                    b.HasIndex("IdTipoRedSocial");

                    b.ToTable("RedesSocialesMunicipio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", b =>
                {
                    b.Property<int>("IdReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporteCiudadano"), 1L, 1);

                    b.Property<DateTime>("FechaPrimerReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstatusReporteCiudadano")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoReporteCiudadano")
                        .HasColumnType("int");

                    b.HasKey("IdReporteCiudadano");

                    b.HasIndex("IdEstatusReporteCiudadano");

                    b.HasIndex("IdTipoReporteCiudadano");

                    b.ToTable("ReportesCiudadanos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ServicioDomicilioPredio", b =>
                {
                    b.Property<int>("IdServicioDomicilioPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicioDomicilioPredio"), 1L, 1);

                    b.Property<double>("Estatus")
                        .HasColumnType("float");

                    b.Property<int>("IdDomicilioPredio")
                        .HasColumnType("int");

                    b.Property<int>("IdServicioPredio")
                        .HasColumnType("int");

                    b.HasKey("IdServicioDomicilioPredio");

                    b.HasIndex("IdDomicilioPredio");

                    b.HasIndex("IdServicioPredio");

                    b.ToTable("ServiciosDomicilioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ServicioPredio", b =>
                {
                    b.Property<int>("IdServicioPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicioPredio"), 1L, 1);

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdServicioPredio");

                    b.ToTable("ServiciosPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoAtencionContacto", b =>
                {
                    b.Property<int>("IdTipoAtencionContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoAtencionContacto"), 1L, 1);

                    b.Property<string>("TipoAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoAtencionContacto");

                    b.ToTable("TiposAtencionesContacto");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoLugarTuristico", b =>
                {
                    b.Property<int>("IdTipoLugarTuristico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoLugarTuristico"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoLugarTuristico");

                    b.ToTable("TiposLugarTuristico");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoPago", b =>
                {
                    b.Property<int>("IdTipoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPago"), 1L, 1);

                    b.Property<string>("Pago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdTipoPago");

                    b.ToTable("TiposPago");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoRedSocial", b =>
                {
                    b.Property<int>("IdTipoRedSocial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoRedSocial"), 1L, 1);

                    b.Property<string>("RedSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoRedSocial");

                    b.ToTable("TiposRedesSociales");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoReporteCiudadano", b =>
                {
                    b.Property<int>("IdTipoReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoReporteCiudadano"), 1L, 1);

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoReporteCiudadano");

                    b.ToTable("TiposReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoTokenLogin", b =>
                {
                    b.Property<int>("IdTipoTokenLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTokenLogin"), 1L, 1);

                    b.Property<string>("TipoToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoTokenLogin");

                    b.ToTable("TiposTokenLogin");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", b =>
                {
                    b.Property<int>("IdTokenActualizarPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenActualizarPassword"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenActualizarPassword");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("TokensActualizarPassword");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", b =>
                {
                    b.Property<int>("IdTokenContadorAccesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenContadorAccesos"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenContadorAccesos");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("TokensContadorAcceso");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenLogin", b =>
                {
                    b.Property<int>("IdTokenLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenLogin"), 1L, 1);

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTokenLogin")
                        .HasColumnType("int");

                    b.Property<bool>("MantenerSesion")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenLogin");

                    b.HasIndex("IdTipoTokenLogin");

                    b.ToTable("TokensLogin");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", b =>
                {
                    b.Property<int>("IdTokenVerificacionCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTokenVerificacionCorreo"), 1L, 1);

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTokenVerificacionCorreo");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("TokensVerificacionCorreo");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCuenta")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ValorCatastralPredio", b =>
                {
                    b.Property<int>("IdValorCatastralPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValorCatastralPredio"), 1L, 1);

                    b.Property<DateTime>("FechaValorCatastral")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInformacionDomicilioPredio")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("IdValorCatastralPredio");

                    b.HasIndex("IdInformacionDomicilioPredio");

                    b.ToTable("ValoresCatastralesPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ValorFiscalPredio", b =>
                {
                    b.Property<int>("IdValorFiscalPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValorFiscalPredio"), 1L, 1);

                    b.Property<DateTime>("FechaValorFiscal")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInformacionDomicilioPredio")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("IdValorFiscalPredio");

                    b.HasIndex("IdInformacionDomicilioPredio");

                    b.ToTable("ValoresFiscalesPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", b =>
                {
                    b.Property<int>("IdVercionReporteCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVercionReporteCiudadano"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdReporteCiudadano")
                        .HasColumnType("int");

                    b.HasKey("IdVercionReporteCiudadano");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdReporteCiudadano");

                    b.ToTable("VercionesReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Alerta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusAlerta", "EstatusAlerta")
                        .WithMany()
                        .HasForeignKey("IdEstatusAlerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("EstatusAlerta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoAgenda", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Agenda", "Agenda")
                        .WithMany("ArchivosAgenda")
                        .HasForeignKey("IdNoticia");

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoLugarTuristico", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.LugarTuristico", "LugarTuristico")
                        .WithMany("ArchivosLugarTuristico")
                        .HasForeignKey("IdLugarTuristico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LugarTuristico");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ArchivoNoticia", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Noticia", "Noticia")
                        .WithMany("ArchivosNoticia")
                        .HasForeignKey("IdNoticia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.CaracteristicaLugarTuristico", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.LugarTuristico", "LugarTuristico")
                        .WithMany("CaracteristicasLugarTuristico")
                        .HasForeignKey("IdLugarTuristico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LugarTuristico");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("Contacto")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.Contacto", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContactoSeguridadPublica", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoAtencionContacto", "TipoAtencionContacto")
                        .WithMany()
                        .HasForeignKey("IdTipoAtencionContacto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAtencionContacto");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("ContadorAcceso")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.ContadorAcceso", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", "Rol")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionAlerta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Alerta", "Alerta")
                        .WithOne("DireccionAlerta")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionAlerta", "IdAlerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionLugarTuristico", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.LugarTuristico", "LugarTuristico")
                        .WithOne("DireccionLugarTuristico")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionLugarTuristico", "IdLugarTuristico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LugarTuristico");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionPropietarioPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.PropietarioPredio", "PropietarioPredio")
                        .WithOne("DireccionPropietarioPredio")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionPropietarioPredio", "IdPropietarioPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropietarioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", "VercionReporteCiudadano")
                        .WithOne("DireccionReporteCiudadano")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionReporteCiudadano", "IdVercionReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VercionReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DireccionUsuario", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany("DireccionesUsuario")
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DomicilioPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Predio", "Predio")
                        .WithOne("DomicilioPredio")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.DomicilioPredio", "IdPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("EstatusCuenta")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusCuenta", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", "VercionReporteCiudadano")
                        .WithMany("EvidenciasReporteCiudadano")
                        .HasForeignKey("IdVercionReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VercionReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EvidenciaSolucionReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", "ReporteCiudadano")
                        .WithMany("EvidenciasSolucionReporteCiudadano")
                        .HasForeignKey("IdReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("ReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.InformacionDomicilioPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.DomicilioPredio", "DomicilioPredio")
                        .WithOne("InformacionDomicilioPredio")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.InformacionDomicilioPredio", "IdDomicilioPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomicilioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.LugarTuristico", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoLugarTuristico", "TipoLugarTuristico")
                        .WithMany()
                        .HasForeignKey("IdTipoLugarTuristico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoLugarTuristico");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Pago", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusPago", "EstatusPago")
                        .WithMany()
                        .HasForeignKey("IdEstatusPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoPago", "TipoPago")
                        .WithMany()
                        .HasForeignKey("IdTipoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("EstatusPago");

                    b.Navigation("TipoPago");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.PagoPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Predio", "Predio")
                        .WithMany("PagosPredio")
                        .HasForeignKey("IdPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.PropietarioPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Predio", "Predio")
                        .WithOne("PropietarioPredio")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.PropietarioPredio", "IdPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.RedSocialMunicipio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.ContactoMunicipio", "ContactoMunicipio")
                        .WithMany("RedesSocialesMunicipio")
                        .HasForeignKey("IdContactoMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoRedSocial", "TipoRedSocial")
                        .WithMany()
                        .HasForeignKey("IdTipoRedSocial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactoMunicipio");

                    b.Navigation("TipoRedSocial");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusReporteCiudadano", "EstatusReporteCiudadano")
                        .WithMany("ReportesCiudadanos")
                        .HasForeignKey("IdEstatusReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoReporteCiudadano", "TipoReporteCiudadano")
                        .WithMany("ReportesCiudadanos")
                        .HasForeignKey("IdTipoReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstatusReporteCiudadano");

                    b.Navigation("TipoReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ServicioDomicilioPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.DomicilioPredio", "DomicilioPredio")
                        .WithMany("ServiciosDomicilioPredio")
                        .HasForeignKey("IdDomicilioPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.ServicioPredio", "ServicioPredio")
                        .WithMany()
                        .HasForeignKey("IdServicioPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DomicilioPredio");

                    b.Navigation("ServicioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("TokenActualizarPassword")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.TokenActualizarPassword", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("TokenContadorAccesos")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.TokenContadorAccesos", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenLogin", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.TipoTokenLogin", "TipoTokenLogin")
                        .WithMany()
                        .HasForeignKey("IdTipoTokenLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTokenLogin");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("TokenVerificacionCorreo")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.TokenVerificacionCorreo", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithOne("Usuario")
                        .HasForeignKey("CityApp.Shared.Entities.BDSqlServerCityApp.Usuario", "IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ValorCatastralPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.InformacionDomicilioPredio", "InformacionDomicilioPredio")
                        .WithMany("ValoresCatastralesPredio")
                        .HasForeignKey("IdInformacionDomicilioPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformacionDomicilioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ValorFiscalPredio", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.InformacionDomicilioPredio", "InformacionDomicilioPredio")
                        .WithMany("ValoresFiscallesPredio")
                        .HasForeignKey("IdInformacionDomicilioPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformacionDomicilioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", b =>
                {
                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", "ReporteCiudadano")
                        .WithMany("VercionesReporteCiudadano")
                        .HasForeignKey("IdReporteCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("ReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Agenda", b =>
                {
                    b.Navigation("ArchivosAgenda");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Alerta", b =>
                {
                    b.Navigation("DireccionAlerta");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ContactoMunicipio", b =>
                {
                    b.Navigation("RedesSocialesMunicipio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Cuenta", b =>
                {
                    b.Navigation("Contacto");

                    b.Navigation("ContadorAcceso");

                    b.Navigation("DireccionesUsuario");

                    b.Navigation("EstatusCuenta");

                    b.Navigation("TokenActualizarPassword");

                    b.Navigation("TokenContadorAccesos");

                    b.Navigation("TokenVerificacionCorreo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.DomicilioPredio", b =>
                {
                    b.Navigation("InformacionDomicilioPredio");

                    b.Navigation("ServiciosDomicilioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.EstatusReporteCiudadano", b =>
                {
                    b.Navigation("ReportesCiudadanos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.InformacionDomicilioPredio", b =>
                {
                    b.Navigation("ValoresCatastralesPredio");

                    b.Navigation("ValoresFiscallesPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.LugarTuristico", b =>
                {
                    b.Navigation("ArchivosLugarTuristico");

                    b.Navigation("CaracteristicasLugarTuristico");

                    b.Navigation("DireccionLugarTuristico");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Noticia", b =>
                {
                    b.Navigation("ArchivosNoticia");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Predio", b =>
                {
                    b.Navigation("DomicilioPredio");

                    b.Navigation("PagosPredio");

                    b.Navigation("PropietarioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.PropietarioPredio", b =>
                {
                    b.Navigation("DireccionPropietarioPredio");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.ReporteCiudadano", b =>
                {
                    b.Navigation("EvidenciasSolucionReporteCiudadano");

                    b.Navigation("VercionesReporteCiudadano");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.Rol", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.TipoReporteCiudadano", b =>
                {
                    b.Navigation("ReportesCiudadanos");
                });

            modelBuilder.Entity("CityApp.Shared.Entities.BDSqlServerCityApp.VercionReporteCiudadano", b =>
                {
                    b.Navigation("DireccionReporteCiudadano");

                    b.Navigation("EvidenciasReporteCiudadano");
                });
#pragma warning restore 612, 618
        }
    }
}
